
server:
  port: 8111



  mvc:
    view:
      prefix: /
      suffix: .jsp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: user-module
